package model.POJOS;
// Generated Dec 28, 2018 3:33:21 PM by Hibernate Tools 4.3.1



/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer idpost;
     private User user;
     private String title;
     private String description;
     private String date;
     private String status;

    public Post() {
    }

	
    public Post(User user) {
        this.user = user;
    }
    public Post(User user, String title, String description, String date, String status) {
       this.user = user;
       this.title = title;
       this.description = description;
       this.date = date;
       this.status = status;
    }
   
    public Integer getIdpost() {
        return this.idpost;
    }
    
    public void setIdpost(Integer idpost) {
        this.idpost = idpost;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


